version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.10.1
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.10.1
        ports:
            - 5601:5601
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.10.1
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
          - ./logstash/log-collector:/centralized-logs
          - ./logs:/services-logs
        depends_on:
            - elasticsearch
        networks:
          - elknetwork
networks:
    elknetwork:
        driver: bridge
